"""
demo_2
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="cell_1")
def cell_1_func():
    # Write your code here…
    
    print("Hello World")

@dag(
    schedule_interval=None,
    start_date=pendulum.from_format("2022-12-14", "YYYY-MM-DD"),
)
def demo_2():
    cell_1 = cell_1_func()

dag_obj = demo_2()
